import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "🏠 Welcome",
    },

    {
      type: "category",
      label: "📱 Mobile Development",
      collapsed: false,
      items: [
        // --- SEPARATOR: DART CORE ---
        {
          type: "html",
          value: `
            <div style="display: flex; align-items: center; margin: 15px 0 5px 0;">
              <div style="flex-grow: 1; height: 1px; background: rgba(128,128,128,0.2);"></div>
              <span style="padding: 0 10px; color: #888; font-weight: bold; font-size: 9px; letter-spacing: 1.5px; text-transform: uppercase;">
                ⚡ Dart Core
              </span>
              <div style="flex-grow: 1; height: 1px; background: rgba(128,128,128,0.2);"></div>
            </div>
          `,
          defaultStyle: true,
        },
        "dart/basic",
        "dart/variable",
        "dart/collection",
        "dart/control-flow",
        "dart/function",
        "dart/oop",
        "dart/asynchronous",

        // --- SEPARATOR: FLUTTER ---
        {
          type: "html",
          value: `
            <div style="display: flex; align-items: center; margin: 20px 0 5px 0;">
              <div style="flex-grow: 1; height: 1px; background: rgba(128,128,128,0.2);"></div>
              <span style="padding: 0 10px; color: #888; font-weight: bold; font-size: 9px; letter-spacing: 1.5px; text-transform: uppercase;">
                📱 Frontend
              </span>
              <div style="flex-grow: 1; height: 1px; background: rgba(128,128,128,0.2);"></div>
            </div>
          `,
          defaultStyle: true,
        },
        "dart/flutter",
        "dart/layout",
        "dart/navigation",
        "dart/input",
        "dart/state",
        "dart/local_storage",

        // --- SEPARATOR: BACKEND & STORAGE ---
        {
          type: "html",
          value: `
            <div style="display: flex; align-items: center; margin: 20px 0 5px 0;">
              <div style="flex-grow: 1; height: 1px; background: rgba(128,128,128,0.2);"></div>
              <span style="padding: 0 10px; color: #888; font-weight: bold; font-size: 9px; letter-spacing: 1.5px; text-transform: uppercase;">
                🗄️ Backend
              </span>
              <div style="flex-grow: 1; height: 1px; background: rgba(128,128,128,0.2);"></div>
            </div>
          `,
          defaultStyle: true,
        },
        "dart/pocketbase",
        "dart/crud",
        "dart/storage",
        "dart/realtime",
        "dart/authentication",
      ],
    },

    {
      type: "category",
      label: "⚙️ Computer Engineering",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "zig",
        },
      ],
    },
  ],
};

export default sidebars;
