import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '🏠 Welcome',
    },

    {
      type: 'category',
      label: '🎯 Dart Ecosystem',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'dart',
        },
      ],
    },

    {
      type: 'category',
      label: '🦀 Rust Core',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'rust',
        },
      ],
    },
  ],
};

export default sidebars;
